name: Comprehensive PR Pipeline

on:
  pull_request:
    types:
      - labeled
  workflow_dispatch:

jobs:
  check-label:
    if: github.event.label.name == 'check'
    uses: ./.github/workflows/python-test.yml

    with:
      command: |
         python3 -m app.workers.poller_worker
    secrets:
      GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
      GMAIL_CREDENTIALS_JSON: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
  # 2. This job runs when the PR is labeled with "merge"
  merge-label:
    if: github.event.label.name == 'merge'
    uses: ./.github/workflows/python-test.yml
    secrets:
      GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
      GMAIL_CREDENTIALS_JSON: ${{ secrets.GMAIL_CREDENTIALS_JSON }}

    with:
      command: |
         python3 -m app.workers.poller_worker
  
  cleanup:
    if: always()
    uses: ./.github/workflows/remove-label.yml
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

